name: Autograding Tests
'on':
- push
- repository_dispatch
permissions:
  checks: write
  actions: read
  contents: read
jobs:
  run-autograding-tests:
    runs-on: ubuntu-latest
    if: github.actor != 'github-classroom[bot]'
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: something
      id: something
      uses: classroom-resources/autograding-io-grader@v1
      with:
        test-name: something
        setup-command: somehtifj
        command: "./soemthing "
        input: sofmdkfj
        expected-output: testing for it
        comparison-method: contains
        timeout: 10
        max-score: 99
    - name: Autograding Reporter
      uses: classroom-resources/autograding-grading-reporter@v1
      env:
        SOMETHING_RESULTS: "${{steps.something.outputs.result}}"
      with:
        runners: something
